version: '3.9'
services:
  # Application
  app:
    build:
      context: ./
      dockerfile: ./docker/dev/app/Dockerfile
    image: lf-app
    container_name: lf-app
    restart: unless-stopped
    logging:
      options:
        max-size: "5k"
    ports:
      - '${FORWARD_VITE_PORT:-5173}:5173'
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker/dev/php/app.ini:/usr/local/etc/php/conf.d/app.ini
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - lf
    depends_on:
      - database

  # Web Server
  web:
    image: nginx:alpine
    container_name: lf-web
    restart: unless-stopped
    logging:
      options:
        max-size: "5k"
    ports:
      - '${FORWARD_NGINX_PORT:-80}:80'
    volumes:
      - ./:/var/www
      - ./docker/dev/nginx:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - lf

  # Database
  database:
    platform: linux/x86_64
    image: mysql:8.0.32
    command: [
      'mysqld',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--default-time-zone=+7:00',
      '--lower-case-table-names=1'
    ]
    container_name: lf-db
    restart: unless-stopped
    logging:
      options:
        max-size: "5k"
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_DATABASE_TEST: ${DB_DATABASE_TESTING}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/dev/mysql/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
      - ./docker/dev/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - lf

  # Mailing Server
  mailpit:
    image: axllent/mailpit
    container_name: lf-mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - lf
    depends_on:
      - database

volumes:
  dbdata:

networks:
  lf:
    driver: bridge