version: '3.9'
services:
  # Application
  app:
    build:
      args:
        user: webuser
        uid: 1000
      context: ./
      dockerfile: ./docker/dev/app/Dockerfile
    image: lf-app
    container_name: lf-app
    restart: unless-stopped
    logging:
      options:
        max-size: "5k"
    ports:
      - '${FORWARD_VITE_PORT:-5173}:5173'
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker/dev/php/app.ini:/usr/local/etc/php/conf.d/app.ini
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - lf

  # Web Server
  web:
    image: nginx:alpine
    container_name: lf-web
    restart: unless-stopped
    logging:
      options:
        max-size: "5k"
    ports:
      - '${FORWARD_NGINX_PORT:-80}:80'
    volumes:
      - ./:/var/www
      - ./docker/dev/nginx:/etc/nginx/conf.d/
    networks:
      - lf

  # Database
  database:
    platform: linux/x86_64
    image: mysql:8.0.32
    command: mysqld --sql_mode=""
    container_name: lf-db
    restart: unless-stopped
    logging:
      options:
        max-size: "5k"
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - lf

  # Mailing Server
  mailpit:
    image: axllent/mailpit
    container_name: lf-mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  dbdata:

networks:
  lf:
    driver: bridge